md-prev:
    build: .
    container_name: "md-prev"
    ports:
        - '8080:8080'
    environment:
        - PORT=8080
    volumes:
        - .:/home/app/md-prev
        - /home/app/md-prev/node_modules
        - www:/home/app/md-prev/out
nginx-proxy:
    image: nginx
    container_name: "nginx"
    ports:
        - '8081:8081'
    volumes:
        - ./nginx:/etc/nginx/conf.d:ro
        - www:/www/app/:ro
    links:
        - 'md-prev'
